version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/yolov8
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    networks:
      - my_network
    restart: unless-stopped

  bot:
    build: .
    volumes:
      - .:/yolov8
    command: ["python", "bot.py"]
    networks:
      - my_network
    env_file:
      - .env
    restart: unless-stopped

networks:
  my_network:
